name: Black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        
    - name: Python Blacken
      uses: piotrpawlaczek/python-blacken@release/stable
      run: |
        pwd
        ls
      with:
        path: '.'
        line-length: 81
